version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: wedding_presence_db
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=asdfasdf
      - POSTGRES_DB=wedding_presence

  api:
    build:
      context: ./
    container_name: wedding_presence_api
    restart: always
    ports:
      - 1324:1323
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=asdfasdf
      - DB_NAME=wedding_presence
    depends_on:
      - db

  web:
    build:
      context: ./internal/web
    container_name: wedding_presence_web
    restart: always
    ports:
      - 3001:3000
    depends_on:
      - api

