version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: wedding_presence_db
    platform: linux/amd64
    restart: always
    environment:
      - POSTGRES_PASSWORD=asdfasdf
      - POSTGRES_DB=wedding_presence

  api:
    build: ./
    container_name: wedding_presence_api
    platform: linux/amd64
    restart: always
    ports:
      - 1323:1323
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=asdfasdf
      - DB_NAME=wedding_presence
    depends_on:
      - db

  web:
    build:
      context: ./internal/web
    container_name: wedding_presence_web
    platform: linux/amd64
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:1323
    depends_on:
      - api

